[window]
opacity = 0.8
startup_mode = "Maximized"

[mouse]
hide_when_typing = true

[terminal.shell]
program = "/opt/homebrew/bin/tmux" # <- Set your path
args = ["new-session", "-A", "-D", "-s", "ðŸ¡ Home"]

[general]
import = ["~/.config/alacritty/themes/monokai_pro.toml"]
