[window]
opacity = 0.8
startup_mode = "Maximized"

[mouse]
hide_when_typing = true

# autostart tmux
[terminal.shell]
program = "/opt/homebrew/bin/tmux" # <- Set your path
args = ["new-session", "-A", "-D", "-s", "ðŸ¡ Home"]

# Thema
[general]
import = ["~/.config/alacritty/themes/gruvbox_dark.toml"]
